export const Administrator_Events = {
    GETPLAYERS_SERVER : 'Admin:Basics:GetPlayers:Server',
    GETPLAYERS_CLIENT : 'Admin:Basics:GetPlayers:Client',
    GETCARS_SERVER : 'Admin:Basics:GetCars:Server',
    GETCARS_CLIENT : 'Admin:Basics:GetCars:Client',
    GETRANK_SERVER : 'Admin:Basics:GetRank:Server',
    GETRANK_CLIENT : 'Admin:Basics:GetRank:Client',
    NOCLIP_CLIENT : 'Admin:Basics:NoClip:Client',
    EVENTS_CLIENT : 'Admin:Basics:Events:Client',
    GETTER_CLIENT : 'Admin:Basics:Getter:Client',
    NOCLIP_SERVER : 'Admin:Basics:NoClip:Server',
    TELEPORTATION: 'Admin:Basics:Teleportation:Server',
    SESSION: 'Admin:Basics:Session:Server',
    SKIN_SET: 'Admin:Basics:Skin:Set:Server',
    SKIN_RESET: 'Admin:Basics:Skin:Reset:Server',
    EVENTS_SERVER : 'Admin:Basics:Events:Server',
    GETTER_SERVER : 'Admin:Basics:Getter:Server',
    EVENTS_SERVER_PARTICLE : 'Admin:Basics:Events:Server:Particle',
    EVENTS_SERVER_VISIBLE : 'Admin:Basics:Events:Server:Visible',
    GETTER_SERVER_CAR : 'Admin:Basics:Teleport:From:Car',
    GETTER_SERVER_PLAYER : 'Admin:Basics:Teleport:From:Player',
    GETTER_SERVER_GOTO_CAR : 'Admin:Basics:Teleport:To:Car',
    GETTER_SERVER_GOTO_PLAYER : 'Admin:Basics:Teleport:To:Player',
    SYNCEDMETA_RANKS: 'Admin:SyncedMeta:Ranks',
    SYNCEDMETA_CARS_ID: 'Admin:SyncedMeta:Cars:ID',
    SYNCEDMETA_PLAYERS: 'Admin:SyncedMeta:Players',
};